<a href="https://colab.research.google.com/github/2303a51498/2303a51498_pds_B08/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1st question

In [1]:
import numpy as np
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)


Matrix A:
 [[ 1  1  9]
 [ 1  9  4]
 [ 6 10  1]]
Matrix B:
 [[4 4 9]
 [4 7 3]
 [9 4 8]]


In [2]:
add_result = np.add(A, B)
print( add_result)

[[ 5  5 18]
 [ 5 16  7]
 [15 14  9]]


In [3]:
sub_result = np.subtract(A, B)
print( sub_result)

[[-3 -3  0]
 [-3  2  1]
 [-3  6 -7]]


In [4]:
manual_add = A[0,0] + B[0,0]
manual_sub = A[0,0] - B[0,0]

print(f"Manual check for position [0,0]: {A[0,0]} + {B[0,0]} = {manual_add}")
print(f"Manual check for position [0,0]: {A[0,0]} - {B[0,0]} = {manual_sub}")

Manual check for position [0,0]: 1 + 4 = 5
Manual check for position [0,0]: 1 - 4 = -3


2nd question

In [5]:
import numpy as np
A = np.random.randint(1, 10, (3, 2))
B = np.random.randint(1, 10, (2, 3))

print("Matrix A (3x2):\n", A)
print("Matrix B (2x3):\n", B)

Matrix A (3x2):
 [[4 5]
 [1 7]
 [9 1]]
Matrix B (2x3):
 [[5 9 8]
 [1 7 4]]


In [6]:
C = np.dot(A, B)
print("Result of A x B (3x3):\n", C)

Result of A x B (3x3):
 [[25 71 52]
 [12 58 36]
 [46 88 76]]


In [7]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Shape of Result:", C.shape)

Shape of A: (3, 2)
Shape of B: (2, 3)
Shape of Result: (3, 3)


In [8]:
manual_check = A[0,0]*B[0,0] + A[0,1]*B[1,0]
print(f"Manual check for C[0,0]: {manual_check} vs {C[0,0]}")

Manual check for C[0,0]: 25 vs 25
