<a href="https://colab.research.google.com/github/2303a51498/2303a51498_pds_B08/blob/main/pds_lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array2d_1= np.array([[3,5,7],[7,3,9]])
array2d_2=np. array([[3,5],[7,3],[4,2]])
print("2d array 1\n", array2d_1)
print("2d array 2\n", array2d_2)
print("dot product:\n", np.dot(array2d_1, array2d_2))


2d array 1
 [[3 5 7]
 [7 3 9]]
2d array 2
 [[3 5]
 [7 3]
 [4 2]]
dot product:
 [[72 44]
 [78 62]]
