<a href="https://colab.research.google.com/github/2303a51498/2303a51498_pds_B08/blob/main/pds_lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
array2d_1= np.array([[3,2,6],[6,8,4]])
array2d_2= np.array([[6,6,4],[2,5,8]])
print("2d array 1:\n", array2d_1)
print("2d array 2:\n", array2d_2)

print("addition:\n",np.add(array2d_1,array2d_2))
print("subtraction of arr1-arr2:\n", np.subtract(array2d_1,array2d_2))
print("subtraction of arr2-arr1:\n", np.subtract(array2d_2,array2d_1))

2d array 1:
 [[3 2 6]
 [6 8 4]]
2d array 2:
 [[6 6 4]
 [2 5 8]]
addition:
 [[ 9  8 10]
 [ 8 13 12]]
subtraction of arr1-arr2:
 [[-3 -4  2]
 [ 4  3 -4]]
subtraction of arr2-arr1:
 [[ 3  4 -2]
 [-4 -3  4]]


In [11]:
import numpy as np
array2d_1= np.array([[3,5,7],[7,3,9]])
array2d_2=np. array([[3,5],[7,3],[4,2]])
print("2d array 1\n", array2d_1)
print("2d array 2\n", array2d_2)
print("dot product:\n", np.dot(array2d_1, array2d_2))


2d array 1
 [[3 5 7]
 [7 3 9]]
2d array 2
 [[3 5]
 [7 3]
 [4 2]]
dot product:
 [[72 44]
 [78 62]]
